### ISSUE TITLE
[Bug] Byaml Editor

### ISSUE THREAD

**Issue by MacClelland** [exelix11/OdysseyEditor#11]
Arrays dont save anymore.

When ItemCap anything is edited or a new Item is added and then saved after reopening the save its gone.
Coins do save and anything else seems to work True/False works too. Only things in arrays dont save anymore.

**Comment by exelix11** [comment]
Yes, can confirm. Thanks for the report. Will be fixed with next release

**Comment by exelix11** [comment]
should be fixed with
https://github.com/exelix11/EditorCore/commit/1e3bb450f3b6ae1747050124c1f4fbf8a29879b4 and 
https://github.com/exelix11/EditorCore/commit/cedd1c202cb37f235e7724c4229fd83a45829ee9

**Comment by MacClelland** [comment]
Damn that was fast. Thanks yes can confirm it's fixed.
Closed.
